# Code your solutions in this file
print("Written by: Shokhjakhon and Eric")
print("Title: Fast and Furious")
print("Setting: Early 2000s")
print("Long ago")
print("Two men were into cars and built their own JDMs")
print("One was a cop and the other one was not")
print("They would go drag racing in the night when there were no cops around")
print("At night they would steal radio's")
print("And they never got caught for it ever")